config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: %I[show]
  resources :products

  root 'products#index'

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :photo

  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: t(".success")
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.with_attached_photo
  end

  # este es el metodo que resuelve el endpoint y retorna un formulario
  # al link_to "Add Product" en formato html
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t(".success")
    else
      flash[:alert] = t(".failed")
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: t(".success")
    else
      flash[:alert] = t(".failed")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other, notice: t(".success")
  end

  private

  def set_product
    @product = Product.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to products_path, alert: error.message, status: :not_found
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t("activerecord.models.category") %></strong>
    <%= category.name %>
  </p>

  <%=
    link_to t("common.edit"),
            edit_category_path(category),
            class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  %>
  <%=
    link_to t("common.destroy"),
            category_path(category),
            turbo_method: :delete,
            turbo_confirm: :delete,
            class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
  %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit t("common.create"),class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium
    cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to t("common.back"), categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t(".title") %></h1>
  </div>

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/flash' %>
    <%= render partial: 'shared/modal' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/component_preview.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "main", "inter-font", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="max-w-7xl p-10 mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>

  <% product.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <input type="submit" value="<%= button_text %>" />
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product' do %>
  <h2><%= product.title %></h2>
  <span>$ <%= product.price%></span>

  <% if product.photo.present? %>
    <%= image_tag product.photo, width: 100 %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h2><%= t(".title") %></h2>

<%= render partial: 'form', locals: { product: @product, button_text: t("common.update") } %>

app/views/products/index.html.erb
<h1><%= t(".title") %></h1>

<%= render @products %>

app/views/products/new.html.erb
<!-- esto es lo que va a devolver el endpoint del enlace -->
<!-- y queremos que lo reciba los tags de turbo frame llamados modal -->
<%= turbo_frame_tag 'modal' do %>

  <!-- register the stimulus controller to able use internal methods in its html nodes -->
  <div data-controller="modal">
    <!-- esta es una capa con el fondo de color oscuro para resaltar el formulario nuewvo -->
    <div
      class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"
      data-action="click->modal#close"
    >
    </div>

    <div
      class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-0"
      data-modal-target="sidebar"
    >
      <!-- close button -->
      <p data-action="click->modal#close">❌</p>

      <h1><%= t(".title") %></h1>

      <%= render partial: 'form', locals: { product: @product, button_text: t("common.create") } %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<h1><%= t("products.show.title") %></h1>
<h2><%= @product.title %></h2>

<%= image_tag @product.photo if @product.photo.present? %>

<p><%= @product.description %></p>
<p><%= @product.price %></p>

<%= link_to t("products.new.title"), edit_product_path(@product) %>
<%= link_to t("products.destroy.title"), product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: t("common.confirm")
} %>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1><%= t("application.name") %></h1>
<% end %>

<!-- Lo que traiga del enlace lo tengo que cargar en el turbo_frame modal -->
<%= link_to t("products.new.title"), new_product_path, data: { turbo_frame: 'modal' } %>
<%= link_to t("categories.index.title"), categories_path %>

app/views/shared/_modal.html.erb
<!-- quiero que se incruste aca -->
<%= turbo_frame_tag 'modal' %>